apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: target-app-proactive
  namespace: nt531-env
spec:
  scaleTargetRef:
    name: target-app
  pollingInterval: 15
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 6
  triggers:
  - type: prometheus
    metadata:
      # Sửa lại địa chỉ Service chuẩn của Quyên
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      threshold: '6'
      query: |
        sum(predicted_traffic_demand)
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Pods
            value: 1
            periodSeconds: 60
          selectPolicy: Min
