apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: target-app-proactive
  namespace: nt531-env
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: target-app # Khớp với tên App của bạn
  pollingInterval: 10
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 8
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://100.97.201.48:9090
      metricName: predicted_traffic_demand
      threshold: '4' 
      query: sum(predicted_traffic_demand)
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0 # Tăng tải ngay lập tức giống Reactive
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 300 # Giữ ổn định 5 phút giống Reactive
          selectPolicy: Min
          policies:
          - type: Pods
            value: 1
            periodSeconds: 60 # Chỉ giảm 1 Pod mỗi phút
