apiVersion: batch/v1
kind: Job
metadata:
  name: chaos-spike-kill-50
  namespace: litmus
spec:
  template:
    spec:
      serviceAccountName: litmus-admin
      containers:
      - name: chaos-tool
        image: bitnami/kubectl:latest
        command:
          - /bin/bash
          - -c
          - |
            echo "Đang đợi 30s để đến đỉnh Spike..."
            sleep 30

            # CHỈNH THỜI GIAN CHẠY (Ví dụ: 300 giây = 5 phút)
            DURATION=300
            END_TIME=$((SECONDS + DURATION))

            echo "BẮT ĐẦU CHIẾN DỊCH PHÁ HOẠI TRONG $DURATION GIÂY!"

            while [ $SECONDS -lt $END_TIME ]; do
              # Lấy danh sách Pod hiện tại
              PODS=($(kubectl get pods -n nt531-env -l app=processing -o jsonpath='{.items[*].metadata.name}'))
              TOTAL=${#PODS[@]}
              KILL_COUNT=$((TOTAL / 2))

              echo "Đang có $TOTAL pods. Xóa $KILL_COUNT pods..."

              for (( i=0; i<$KILL_COUNT; i++ )); do
                kubectl delete pod ${PODS[$i]} -n nt531-env --wait=false
              done

              # Nghỉ 15 giây trước khi "quét" tiếp đợt mới (để Pod kịp tạo lại)
              echo "Đợi 15s để hệ thống tự chữa lành trước đợt phá tiếp theo..."
              sleep 15
            done

            echo "KẾT THÚC BÀI TEST CHẠY 300s."
      restartPolicy: Never

