apiVersion: v1
kind: Service
metadata:
  name: proactive-controller-svc
  namespace: monitoring
  labels:
    app: proactive-controller
spec:
  ports:
    - name: metrics
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proactive-controller-svc
  namespace: monitoring
subsets:
  - addresses:
      - ip: 100.97.201.48 # IP Tailscale của máy NT531Q21
    ports:
      - name: metrics
        port: 8001
