# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: external_scaler.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'external_scaler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65xternal_scaler.proto\x12\x0e\x65xternalscaler\"2\n\x0fScaledObjectRef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\"H\n\x15GetMetricSpecResponse\x12/\n\x0bmetricSpecs\x18\x01 \x03(\x0b\x32\x1a.externalscaler.MetricSpec\"4\n\nMetricSpec\x12\x12\n\nmetricName\x18\x01 \x01(\t\x12\x12\n\ntargetSize\x18\x02 \x01(\x03\"\'\n\x11GetMetricsRequest\x12\x12\n\nmetricName\x18\x01 \x01(\t\"G\n\x12GetMetricsResponse\x12\x31\n\x0cmetricValues\x18\x01 \x03(\x0b\x32\x1b.externalscaler.MetricValue\"6\n\x0bMetricValue\x12\x12\n\nmetricName\x18\x01 \x01(\t\x12\x13\n\x0bmetricValue\x18\x02 \x01(\x03\"\"\n\x10IsActiveResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\x8d\x02\n\x0e\x45xternalScaler\x12W\n\rGetMetricSpec\x12\x1f.externalscaler.ScaledObjectRef\x1a%.externalscaler.GetMetricSpecResponse\x12S\n\nGetMetrics\x12!.externalscaler.GetMetricsRequest\x1a\".externalscaler.GetMetricsResponse\x12M\n\x08IsActive\x12\x1f.externalscaler.ScaledObjectRef\x1a .externalscaler.IsActiveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'external_scaler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCALEDOBJECTREF']._serialized_start=41
  _globals['_SCALEDOBJECTREF']._serialized_end=91
  _globals['_GETMETRICSPECRESPONSE']._serialized_start=93
  _globals['_GETMETRICSPECRESPONSE']._serialized_end=165
  _globals['_METRICSPEC']._serialized_start=167
  _globals['_METRICSPEC']._serialized_end=219
  _globals['_GETMETRICSREQUEST']._serialized_start=221
  _globals['_GETMETRICSREQUEST']._serialized_end=260
  _globals['_GETMETRICSRESPONSE']._serialized_start=262
  _globals['_GETMETRICSRESPONSE']._serialized_end=333
  _globals['_METRICVALUE']._serialized_start=335
  _globals['_METRICVALUE']._serialized_end=389
  _globals['_ISACTIVERESPONSE']._serialized_start=391
  _globals['_ISACTIVERESPONSE']._serialized_end=425
  _globals['_EXTERNALSCALER']._serialized_start=428
  _globals['_EXTERNALSCALER']._serialized_end=697
# @@protoc_insertion_point(module_scope)
