apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: target-app-grpc
  namespace: nt531-env
spec:
  scaleTargetRef:
    name: target-app

  minReplicaCount: 2
  maxReplicaCount: 8

  triggers:
  - type: external
    metadata:
      scalerAddress: predictive-controller-service.monitoring.svc.cluster.local:50051
      metricName: future_load
      targetValue: "8"
