apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: target-app-monitor
  namespace: monitoring
  labels:
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: processing # Khớp với label của Service
  namespaceSelector:
    any: true # Quét tất cả các namespace để tìm App
  endpoints:
  - port: http
    path: /metrics
    interval: 1s
